version: "3.7"

services:
  ubuntu-qt5-java8:
    container_name: ast-ubuntu-qt5-java8
    image: astvision/ubuntu-qt5-java8
    hostname: ast-ubuntu-qt5-java8
    restart: always
    networks:
      - ast_starter
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

  ubuntu-qt5-java17:
    container_name: ast-ubuntu-qt5-java17
    image: astvision/ubuntu-qt5-java17
    hostname: ast-ubuntu-qt5-java17
    restart: always
    networks:
      - ast_starter
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

networks:
  ast_starter:
    driver: bridge
